<style>
    .webone-section {
        margin-bottom: 40px;
    }
</style>

<div class="webone-wrapper">

    <div class="webone-header">
        <div class="webone-text-center">
            <img src="<?php echo WEBONE_PLUGIN_URL . 'assets/webone-logo.png'; ?>"/>
        </div>
        <h1 class="webone-text-center">وب وان</h1>
        <h2 class="webone-text-center">
            افزونه وردپرس مهاجرت به وب وان
        </h2>
        <h5 class="webone-text-center">
            نگارش:
            <?php echo WEBONE_PLUGIN_VERSION; ?>
        </h5>
    </div>

    <div class="webone-body">
        <div class="webone-section">
            <h1>درباره وب وان</h1>
            <p>
                وب وان مجموعه کاملی از خدمات و محصولات شامل بازاریابی دیجیتال, سئو, سوشال مدیا,طراحی سایت, مارکت پلیس و
                پیامک انبوه است تا نیازهای شما را در تمام مراحل مرتفع کند.
            </p>
        </div>

        <div class="webone-section">
            <h1>درباره افزونه</h1>
            <p>
                این افزونه برای ارائه وب سرویس های مورد نیاز به سایت وب وان با هدف تسهیل در مهاجرت به سیستم مدیریت
                محتوای اختصاصی وب وان ساخته شده است. وب سرویس های ارائه شده توسط افزونه به شرح زیر است:
                <ol>
                    <li>
                        وب سرویس دریافت دسته بندی های مطالب
                    </li>
                    <li>
                        وب سرویس دریافت مطالب سایت
                    </li>
                    <li>
                        وب سرویس دریافت دسته بندی های محصولات
                    </li>
                    <li>
                        وب سرویس دریافت محصولات
                    </li>
                </ol>
            </p>
        </div>

        <div class="webone-section">
            <h1>پشتیبانی</h1>
            <p>
                در صورت داشتن هرگونه سوال، گزارش خطای رخ داده و ... می توانید با پشتیبانی
                <a href="https://webone.co" target="_blank">سایت وب وان</a>
                تماس بگیرید.
            </p>
        </div>
    </div>

</div>